# Generated by Django 5.2.10 on 2026-02-13 00:00

import random
import string
from django.db import migrations, models


def _generate_tracking_id(existing):
    prefix = "CMP-"
    alphabet = string.ascii_uppercase + string.digits
    rng = random.SystemRandom()

    while True:
        suffix = "".join(rng.choice(alphabet) for _ in range(6))
        candidate = f"{prefix}{suffix}"
        if candidate not in existing:
            return candidate


def populate_tracking_ids(apps, schema_editor):
    Complaint = apps.get_model("complaints", "Complaint")
    existing = set(
        Complaint.objects.exclude(tracking_id__isnull=True).values_list("tracking_id", flat=True)
    )

    for complaint in Complaint.objects.filter(tracking_id__isnull=True):
        tracking_id = _generate_tracking_id(existing)
        complaint.tracking_id = tracking_id
        complaint.save(update_fields=["tracking_id"])
        existing.add(tracking_id)


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0005_feedback_resolution_status_alter_complaint_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="tracking_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=25,
                null=True,
                unique=True,
            ),
        ),
        migrations.RunPython(populate_tracking_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="complaint",
            name="tracking_id",
            field=models.CharField(
                db_index=True,
                editable=False,
                max_length=25,
                unique=True,
            ),
        ),
    ]
